"""
Report Generator — Institutional Biotech Diligence Memo.

Converts an AuditResponse into a structured Markdown document suitable for
investment committee review, internal diligence memos, and fund analysis.

Tone: institutional, analytical, risk-aware, scientifically cautious.
This is NOT investment advice. All outputs are model estimates.
"""

from __future__ import annotations

from typing import List

from app.models.schemas import AuditRequest, AuditResponse


def _fmt_m(value: float) -> str:
    """Format USD value in millions with 1 decimal."""
    return f"${value / 1_000_000:.1f}M"


def _fmt_pct(value: float) -> str:
    return f"{value:.1%}"


def _fmt_months(value: float) -> str:
    return f"{value:.1f} months"


def _risk_color_label(risk: str) -> str:
    mapping = {
        "Low Risk": "**Low Risk**",
        "Moderate Risk": "**Moderate Risk**",
        "High Risk": "**High Risk**",
        "Critical Risk": "**Critical Risk**",
    }
    return mapping.get(risk, risk)


# ---------------------------------------------------------------------------
# Section generators
# ---------------------------------------------------------------------------

def _header(r: AuditResponse, req: AuditRequest) -> str:
    mv = r.model_version
    return f"""# CatalystLens Biotech Capital-to-Catalyst Audit

**Company:** {r.company_name} ({r.ticker})
**Lead Asset:** {r.asset_name}
**Indication:** {req.clinical.indication}
**Trial Phase:** {req.clinical.trial_phase.replace("_", " ").title()}
**Audit Timestamp:** {r.audit_timestamp}
**Model:** v{mv.backend_version} | Coefficient Set: `{mv.coefficient_set}` | Config Hash: `{mv.config_hash}` | Simulations: {mv.n_simulations:,} (seed {mv.random_seed})

> **Disclaimer:** This report is generated by CatalystLens, a probabilistic
> modelling system. All outputs are *model estimates*, not predictions, valuations,
> or investment recommendations. Cox coefficients, signal weights, and phase
> priors are configurable MVP assumptions that have not been trained on historical
> biotech outcome data. This document does not constitute investment advice.
> Outputs should complement, not replace, professional analyst diligence.
>
> **Calibration status:** {mv.calibration_status}"""


def _executive_summary(r: AuditResponse, req: AuditRequest) -> str:
    s = r.final_summary
    ctc = r.capital_to_catalyst
    sol = r.solvency
    pos = r.success_probability
    val = r.valuation
    clin = req.clinical

    # Investment-style interpretation
    cashout_pct = _fmt_pct(ctc.probability_cashout_before_catalyst)
    pos_pct = _fmt_pct(pos.posterior_mean)

    if ctc.probability_cashout_before_catalyst >= 0.60:
        fin_interp = (
            f"The company's lead program presents a materially constrained financing profile. "
            f"Under the current burn trajectory, the modelled probability of capital exhaustion "
            f"before the stated {clin.catalyst_type.replace('_', ' ')} is {cashout_pct}. "
            f"The investment case therefore appears less dependent on technical failure alone "
            f"and more dependent on the company's ability to finance through clinical data "
            f"without excessive dilution."
        )
    elif ctc.probability_cashout_before_catalyst >= 0.35:
        fin_interp = (
            f"The company presents moderate capital-to-catalyst risk. While the modelled "
            f"probability of reaching the {clin.catalyst_type.replace('_', ' ')} before "
            f"cash exhaustion is {_fmt_pct(ctc.probability_reaches_catalyst)}, there remains "
            f"a {cashout_pct} probability that refinancing will be required before the data "
            f"event. Dilution risk is a non-trivial component of the risk profile."
        )
    else:
        fin_interp = (
            f"The company appears sufficiently capitalised to reach the modelled catalyst "
            f"window under base-case assumptions. The primary risk appears to be technical "
            f"rather than financial, with a {cashout_pct} modelled probability of capital "
            f"exhaustion before the {clin.catalyst_type.replace('_', ' ')}."
        )

    return f"""## A. Executive Investment Summary

{fin_interp}

### Summary of Key Questions

| Question | Finding |
|---|---|
| What is the company claiming? | {sol.simple_runway_months:.0f}-month runway; {clin.stated_months_to_catalyst:.0f}-month stated catalyst timeline |
| What does the model estimate? | {sol.median_failure_time:.0f}-month modelled financial clock; {r.milestone_timing.p50_months:.0f}-month modelled catalyst |
| Where is the main risk? | {s.primary_risk_factor} |
| Is the limit science, timing, or capital? | {s.primary_risk_factor} (primary), {s.secondary_risk_factor} (secondary) |
| Overall risk classification | {_risk_color_label(s.risk_classification)} |

### Key Finding

{s.key_finding}

### Critical Metric

> **Modelled probability of cash exhaustion before stated catalyst: {cashout_pct}**
> **Modelled Bayesian posterior PoS: {pos_pct}**
> **Financing-adjusted rNPV: {_fmt_m(val.financing_adjusted_rnpv)}**"""


def _ic_snapshot(r: AuditResponse, req: AuditRequest) -> str:
    s = r.final_summary
    sol = r.solvency
    ctc = r.capital_to_catalyst
    pos = r.success_probability
    disc = r.disclosure_consistency
    val = r.valuation

    dilution_label = (
        "Low" if ctc.probability_cashout_before_catalyst < 0.30
        else "Moderate" if ctc.probability_cashout_before_catalyst < 0.60
        else "High"
    )

    return f"""## B. Investment Committee Snapshot

| Category | Finding | Interpretation |
|---|---|---|
| Cash Position | {_fmt_m(req.financial.cash_on_hand)} | Reported cash and equivalents |
| Marketable Securities | {_fmt_m(req.financial.marketable_securities)} | Additional liquidity |
| Total Modelled Liquidity | {_fmt_m(sol.total_liquidity)} | Available liquidity base |
| Quarterly Burn | {_fmt_m(req.financial.quarterly_operating_cash_burn)} | Current operating cash consumption |
| Monthly Burn | {_fmt_m(sol.monthly_burn)} | Estimated monthly run-rate |
| Simple Runway | {sol.simple_runway_months:.0f} months | Static cash / burn estimate |
| Modelled Financial Clock | {sol.median_failure_time:.0f} months | Cox-adjusted survival median |
| Stated Catalyst Timing | {req.clinical.stated_months_to_catalyst:.0f} months | Management-disclosed milestone |
| Modelled Catalyst Timing | {r.milestone_timing.p50_months:.0f} months (median) | Simulation-adjusted milestone |
| Cashout Before Catalyst | {_fmt_pct(ctc.probability_cashout_before_catalyst)} | Core capital-to-catalyst risk |
| Posterior PoS | {_fmt_pct(pos.posterior_mean)} | Bayesian updated technical PoS |
| Dilution Risk | {dilution_label} | Refinancing pressure assessment |
| Disclosure Gap | {disc.gap_classification.title()} | Narrative vs structured audit |
| Overall Risk | {_risk_color_label(s.risk_classification)} | Final model classification |"""


def _capital_runway_section(r: AuditResponse, req: AuditRequest) -> str:
    sol = r.solvency
    fin = req.financial

    covariate_rows = "\n".join(
        f"| {k.replace('_', ' ').title()} | {v:+.4f} |"
        for k, v in sol.covariate_contributions.items()
    )

    # Build survival table (selected months)
    survival_months = [3, 6, 9, 12, 18, 24, 36, 48]
    curve_dict = {sp.month: sp for sp in sol.survival_curve}
    survival_rows = ""
    for m in survival_months:
        if m in curve_dict:
            sp = curve_dict[m]
            survival_rows += (
                f"| {m} | {_fmt_pct(sp.survival_probability)} | "
                f"{_fmt_pct(sp.implied_cashout_risk)} |\n"
            )

    total_liq = sol.total_liquidity
    market_cap = fin.market_cap

    return f"""## C. Capital Structure and Runway Analysis

### Liquidity and Burn Summary

| Metric | Value | Notes |
|---|---|---|
| Cash and Equivalents | {_fmt_m(fin.cash_on_hand)} | Reported cash position |
| Marketable Securities | {_fmt_m(fin.marketable_securities)} | Available secondary liquidity |
| **Total Modelled Liquidity** | **{_fmt_m(total_liq)}** | Primary analysis base |
| Quarterly Operating Burn | {_fmt_m(fin.quarterly_operating_cash_burn)} | Most recent quarter |
| Monthly Burn Estimate | {_fmt_m(sol.monthly_burn)} | Quarterly ÷ 3 |
| Debt | {_fmt_m(fin.debt)} | Reported obligations |
| Market Capitalisation | {_fmt_m(market_cap)} | Reference for refinancing capacity |
| Going-Concern Language | {"Yes — elevated risk flag" if fin.going_concern_flag else "Not detected"} | SEC filing indicator |
| Recent Financing (≤6mo) | {"Yes" if fin.recent_financing_flag else "No"} | Capital raise recency |
| Months Since Last Raise | {fin.months_since_last_raise:.0f} months | Financing runway context |

### Simple vs Modelled Runway

**Simple runway** (cash / burn) = **{sol.simple_runway_months:.1f} months**

Simple runway provides a static estimate of liquidity duration assuming
constant burn and no external financing. The Cox-style survival model adjusts
this estimate by incorporating financing risk covariates — burn acceleration,
market conditions, debt burden, market capitalisation relative to cash, and
going-concern status — that may accelerate or reduce the probability of capital
exhaustion.

**Modelled median financial failure time** = **{sol.median_failure_time:.1f} months**
**Cox risk multiplier** = **{sol.risk_multiplier:.3f}x** baseline hazard

> A risk multiplier above 1.0 indicates this company faces higher-than-baseline
> financing failure risk. A multiplier below 1.0 indicates lower-than-baseline risk.

### Cox Covariate Contributions to Risk

| Covariate | Log-Hazard Contribution |
|---|---:|
{covariate_rows}
| **Total Linear Predictor** | **{sol.linear_predictor:+.4f}** |

### Modelled Survival Curve

| Month | Survival Probability | Implied Cashout Risk |
|---:|---:|---:|
{survival_rows}

> **Model note:** These survival probabilities represent the modelled probability
> that the company retains access to capital at each time horizon. They do NOT
> incorporate the probability of technical success or pipeline value. They reflect
> financing survival only."""


def _burn_regime_section(r: AuditResponse, req: AuditRequest) -> str:
    br = r.burn_regime
    fin = req.financial

    if not br.burn_series:
        return "## D. Burn Rate and Regime Analysis\n\n_Insufficient burn history data._"

    rows = ""
    for i, (q, burn) in enumerate(zip(br.quarters, br.burn_series)):
        qoq = br.quarterly_pct_changes[i]
        qoq_str = f"{qoq:+.1%}" if qoq is not None else "—"
        rows += f"| {q} | {_fmt_m(burn)} | {qoq_str} |\n"

    cp_note = (
        f"Change point(s) detected at quarter index(es): {br.changepoint_indices}"
        if br.changepoint_indices
        else "No structural break detected."
    )

    return f"""## D. Burn Rate Quality and Regime Shift Analysis

### Quarterly Burn History

| Quarter | Operating Cash Burn | QoQ Change |
|---|---:|---:|
{rows}

**Detected Change Points:** {cp_note}
**Mean QoQ Burn Acceleration:** {br.burn_acceleration:+.1%}
**Current Burn Regime:** {br.regime.upper()}

### Regime Interpretation

{br.regime_interpretation}

> **Analytical note:** Burn acceleration is particularly relevant in
> clinical-stage biotechnology because transition from dose escalation to
> expansion cohorts, Phase 1 to Phase 2 conversion, or single-site to
> multi-site activation can materially increase operating cash consumption
> without being captured in trailing burn averages. Stated runway guidance
> based on prior-period burn may therefore substantially overstate remaining
> time under an accelerating regime."""


def _clinical_catalyst_section(r: AuditResponse, req: AuditRequest) -> str:
    clin = req.clinical
    mt = r.milestone_timing
    enroll_pct = mt.enrollment_fraction

    return f"""## E. Clinical Catalyst Analysis

### Trial Profile

| Variable | Input | Model Interpretation |
|---|---|---|
| Asset / Program | {clin.asset_name} | Program analysed |
| Indication | {clin.indication} | Disease / therapeutic area |
| Trial Phase | {clin.trial_phase.replace("_", " ").title()} | Development stage |
| Trial Status | {clin.trial_status.replace("_", " ").title()} | Operational status |
| Catalyst Type | {clin.catalyst_type.replace("_", " ").title()} | Defining milestone |
| Stated Catalyst Timeline | {clin.stated_months_to_catalyst:.0f} months | Management estimate |
| Enrollment Target | {clin.enrollment_target:,} patients | Trial power basis |
| Enrollment Completed | {clin.enrollment_completed:,} patients ({enroll_pct:.0%}) | Current enrolment progress |
| Enrollment Rate | {clin.enrollment_rate_per_month:.1f} patients/month | Current accrual pace |
| Number of Sites | {clin.number_of_sites} | Operational site count |
| Indication Complexity | {clin.indication_complexity_score:.1f}/1.0 | Patient identification difficulty |
| Endpoint Complexity | {clin.endpoint_complexity_score:.1f}/1.0 | Readout complexity and lag |
| Regulatory Complexity | {clin.regulatory_complexity_score:.1f}/1.0 | Regulatory pathway difficulty |

### Milestone Timing Distribution (Gamma Model)

The model treats the stated catalyst date as a management-guided estimate, then
applies delay uncertainty using a Gamma-distributed milestone timing model. This
captures the right-skewed nature of clinical development delays: most trials
run broadly on schedule, but a meaningful minority experience extended delays
due to enrollment shortfalls, endpoint revisions, or regulatory feedback.

| Metric | Value |
|---|---:|
| Modelled Delay Factor | {mt.delay_factor:.2f}x stated timeline |
| Adjusted Mean Timeline | {_fmt_months(mt.adjusted_mean_months)} |
| Enrollment Remaining | {_fmt_months(mt.enrollment_remaining_months)} |
| Primary Completion Estimate | {_fmt_months(mt.primary_completion_months)} |
| Public Readout Lag | {_fmt_months(mt.public_readout_lag_months)} |
| Public Readout Estimate | {_fmt_months(mt.public_readout_months)} |
| Gamma α (shape) | {mt.gamma_alpha:.3f} |
| Gamma β (rate) | {mt.gamma_beta_rate:.5f} |
| **P5 (Fast Case)** | **{_fmt_months(mt.p5_months)}** |
| P25 | {_fmt_months(mt.p25_months)} |
| **P50 (Median)** | **{_fmt_months(mt.p50_months)}** |
| P75 | {_fmt_months(mt.p75_months)} |
| **P95 (Slow Case)** | **{_fmt_months(mt.p95_months)}** |

> **Enrollment note:** With {enroll_pct:.0%} of the target enrolled, there are
> approximately {mt.enrollment_remaining_months:.0f} months of enrollment remaining
> at the current accrual rate of {clin.enrollment_rate_per_month:.1f} patients/month.
> The minimum possible catalyst time cannot be shorter than this enrollment
> completion timeline plus post-completion follow-up. Public readout is modeled
> separately from primary completion, adding data cleaning, analysis, and
> disclosure lag assumptions."""


def _bayesian_pos_section(r: AuditResponse, req: AuditRequest) -> str:
    pos = r.success_probability
    ci_l = pos.credible_interval_lower
    ci_u = pos.credible_interval_upper

    pos_rows = ""
    for signal, weight in pos.applied_positive_weights.items():
        pos_rows += f"| {signal.replace('_', ' ').title()} | Yes | {weight:.2f} | +{weight:.2f} to α |\n"

    neg_rows = ""
    for signal, weight in pos.applied_negative_weights.items():
        neg_rows += f"| {signal.replace('_', ' ').title()} | Yes | {weight:.2f} | +{weight:.2f} to β |\n"

    if not pos_rows:
        pos_rows = "| _(None present)_ | — | — | — |\n"
    if not neg_rows:
        neg_rows = "| _(None present)_ | — | — | — |\n"

    delta_pos = pos.posterior_mean - pos.prior_mean
    delta_direction = "upward" if delta_pos > 0 else "downward"

    return f"""## F. Bayesian Probability of Technical Success

The model begins with a phase-specific Beta distribution prior encoding the
historical industry-wide probability of technical success from the stated
development stage to regulatory approval. It then updates this prior using
weighted trial-specific evidence signals.

### Positive Evidence Signals

| Signal | Present? | Weight | Posterior Effect |
|---|---|---:|---|
{pos_rows}

### Negative Evidence Signals

| Signal | Present? | Weight | Posterior Effect |
|---|---|---:|---|
{neg_rows}

### Posterior Summary

| Metric | Value |
|---|---:|
| Phase-Specific Prior | Beta({pos.alpha_prior:.1f}, {pos.beta_prior:.1f}) |
| Prior Mean PoS | {_fmt_pct(pos.prior_mean)} |
| Evidence Update | +{sum(pos.applied_positive_weights.values()):.2f} to α, +{sum(pos.applied_negative_weights.values()):.2f} to β |
| Posterior Distribution | Beta({pos.alpha_posterior:.1f}, {pos.beta_posterior:.1f}) |
| **Posterior Mean PoS** | **{_fmt_pct(pos.posterior_mean)}** |
| {pos.credible_interval_pct:.0f}% Credible Interval | {_fmt_pct(ci_l)} – {_fmt_pct(ci_u)} |

The evidence signals shifted the posterior {delta_direction} by {abs(delta_pos):.1%} relative
to the phase prior.

> **Model note:** The posterior PoS should be interpreted as a model-updated
> estimate based on available trial-specific signals. It reflects the Beta-binomial
> framework's weighted assessment of the evidence, not a regulatory probability
> of approval or a commercial success probability. Signal weights are untrained
> MVP assumptions configurable in config.py."""


def _ctc_section(r: AuditResponse, req: AuditRequest) -> str:
    ctc = r.capital_to_catalyst
    val = r.valuation
    fin = req.financial

    dilution_pct = _fmt_pct(req.valuation.expected_dilution_if_refinanced)
    need_before_pct = _fmt_pct(ctc.probability_cashout_before_catalyst)
    funded_pct = _fmt_pct(ctc.probability_reaches_catalyst)

    return f"""## G. Capital-to-Catalyst Gap Analysis

This is the core output of the CatalystLens model. It answers the central
question: **Will the company remain funded long enough to reach the milestone
its valuation depends on?**

### Gap Distribution

| Metric | Value | Interpretation |
|---|---:|---|
| Median Financial Failure Time | {_fmt_months(ctc.median_financial_failure_time)} | Modelled financing clock (50th pct) |
| Median Catalyst Time | {_fmt_months(ctc.median_catalyst_time)} | Modelled scientific clock (50th pct) |
| Median Gap (T_fin − T_sci) | {_fmt_months(ctc.median_gap_months)} | Positive = funded beyond catalyst |
| 5th Percentile Gap | {_fmt_months(ctc.p5_gap_months)} | Downside timing case |
| 95th Percentile Gap | {_fmt_months(ctc.p95_gap_months)} | Upside timing case |
| **P(Reaches Catalyst Before Cashout)** | **{funded_pct}** | Core success-through-financing metric |
| **P(Cashout Before Catalyst)** | **{need_before_pct}** | Core financing failure measure |

### Risk Classification: {_risk_color_label(ctc.risk_classification)}

{ctc.interpretation}

{"### Central Risk Statement" if ctc.median_gap_months < 0 else "### Financing Position"}

{"The central risk is a **capital-to-catalyst mismatch**: the modelled clinical timeline extends beyond the company's financing capacity under the current burn regime. The company would need to raise additional capital before the catalyst window to avoid exhausting its existing liquidity." if ctc.median_gap_months < 0 else f"The company appears sufficiently capitalised to reach the modelled median catalyst window. However, a {need_before_pct} probability of cashout before catalyst represents a non-trivial tail risk, particularly in downside timing scenarios (P5 gap: {_fmt_months(ctc.p5_gap_months)})."}"""


def _dilution_section(r: AuditResponse, req: AuditRequest) -> str:
    val = r.valuation
    dilution = req.valuation.expected_dilution_if_refinanced

    return f"""## H. Dilution and Refinancing Risk

Financing risk is not binary. A company may survive to the catalyst only by
raising capital at unfavourable terms, which can materially reduce expected
value captured by current shareholders even in a successful clinical outcome.

### Financing Scenario Probability Table

| Scenario | Modelled Probability | Estimated Effect |
|---|---:|---|
| Funded through catalyst | {_fmt_pct(val.p_funded_through_catalyst)} | Lower dilution risk; full option value preserved |
| Clean refinancing before catalyst | {_fmt_pct(val.p_refinancing_success)} | Market-terms dilution; execution risk to financing timing |
| Distressed / below-market refinancing | {_fmt_pct(val.p_distressed_financing)} | Severe shareholder impairment risk |
| Program discontinuation / failed financing | {_fmt_pct(val.p_program_discontinuation)} | Program stalls; valuation collapses to downside case |

**Assumed dilution if refinanced:** {_fmt_pct(dilution)}
**Financing Risk Discount to rNPV:** {_fmt_m(val.financing_risk_discount)}

This financing risk discount represents the modelled erosion of expected value
attributable to the probability of needing to raise capital before the catalyst,
diluting existing shareholders in the process."""


def _disclosure_section(r: AuditResponse, req: AuditRequest) -> str:
    disc = r.disclosure_consistency

    gap_rows = ""
    all_keys = sorted(set(disc.narrative_normalized.keys()) | set(disc.audit_normalized.keys()))
    for key in all_keys:
        narr = disc.narrative_normalized.get(key, 0.0)
        aud = disc.audit_normalized.get(key, 0.0)
        gap = disc.category_gaps.get(key, 0.0)
        gap_str = f"{gap:+.3f}"
        gap_rows += f"| {key.replace('_', ' ').title()} | {narr:.3f} | {aud:.3f} | {gap_str} |\n"

    return f"""## I. Disclosure Consistency / Narrative Gap Analysis

The disclosure consistency module compares the company's narrative framing
(as represented by probability-like scores over risk categories) with the
structured quantitative model output using Jensen-Shannon Divergence (JSD).

JSD is symmetric and bounded [0, 1]: 0 = perfect alignment, 1 = complete divergence.

### Category-Level Gap Table

| Category | Narrative Score | Structured Audit | Gap (N−A) |
|---|---:|---:|---:|
{gap_rows}

### Divergence Metrics

| Metric | Value |
|---|---:|
| Jensen-Shannon Divergence | {disc.jsd_score:.4f} |
| Mean Absolute Raw Gap | {disc.mean_absolute_gap:.4f} |
| Optimism Bias | {disc.optimism_bias:+.4f} |
| Maximum Category Gap | {disc.max_category_gap:.4f} |
| Combined Gap Score | {disc.combined_gap_score:.4f} |
| KL(Narrative ∥ Audit) | {disc.kl_narrative_vs_audit:.4f} |
| KL(Audit ∥ Narrative) | {disc.kl_audit_vs_narrative:.4f} |
| **Disclosure Gap Classification** | **{disc.gap_classification.upper()}** |

### Interpretation

{disc.interpretation}

> **Important:** A material disclosure gap does not imply misconduct, selective
> disclosure, or misleading communications. It indicates that management's
> narrative framing of the company's risk profile is materially more favourable
> than the structured quantitative model estimates. Investors should weigh this
> divergence when evaluating forward guidance and stated milestones."""


def _valuation_section(r: AuditResponse, req: AuditRequest) -> str:
    val = r.valuation
    v_input = req.valuation

    return f"""## J. Unified Expected Value / Risk-Adjusted NPV

For each simulation, the model: (1) samples a PoS from the Beta posterior;
(2) samples binary clinical success; (3) determines whether the company is
funded at the catalyst; (4) applies a time discount; and (5) applies a
dilution/financing penalty if refinancing is required.

### Valuation Decomposition

| Valuation Metric | Value | Notes |
|---|---:|---|
| Asset Value on Success (input) | {_fmt_m(v_input.asset_value_success)} | User-supplied assumption |
| Downside Value (input) | {_fmt_m(v_input.downside_value)} | Residual value on failure |
| Annual Discount Rate (input) | {_fmt_pct(v_input.annual_discount_rate)} | Risk-adjusted discount rate |
| Technical-Risk-Only rNPV | {_fmt_m(val.technical_risk_only_rnpv)} | PoS × discount, no financing risk |
| Financing-Adjusted rNPV | {_fmt_m(val.financing_adjusted_rnpv)} | Full simulation mean value |
| **Financing Risk Discount** | **{_fmt_m(val.financing_risk_discount)}** | Value erosion from financing risk |

### Simulated Value Distribution

| Metric | Value | Interpretation |
|---|---:|---|
| Mean Simulated Value | {_fmt_m(val.mean_value)} | Expected value across simulations |
| Median Simulated Value | {_fmt_m(val.median_value)} | Median outcome |
| 5th Percentile Value | {_fmt_m(val.p5_value)} | Downside case |
| 95th Percentile Value | {_fmt_m(val.p95_value)} | Upside case |
| Probability of Downside Case | {_fmt_pct(val.probability_downside)} | P(value ≤ downside) |
| Probability of High-Upside Case | {_fmt_pct(val.probability_high_upside)} | P(value > {_fmt_m(val.high_upside_threshold)}) |

The difference between technical-risk-only rNPV ({_fmt_m(val.technical_risk_only_rnpv)})
and financing-adjusted rNPV ({_fmt_m(val.financing_adjusted_rnpv)}) represents the
modelled value erosion attributable to financing risk, clinical delay, and dilution
pressure — totalling **{_fmt_m(val.financing_risk_discount)}**.

> **Important:** rNPV outputs are highly sensitive to the user-supplied
> asset_value_success and discount rate. These are assumptions, not model
> outputs. Small changes in asset value can produce large changes in rNPV."""


def _scenario_section(r: AuditResponse, req: AuditRequest) -> str:
    scenarios = r.final_summary.scenarios
    if not scenarios:
        return "## K. Scenario Analysis\n\n_Scenario analysis not available._"

    rows = ""
    for sc in scenarios:
        rows += (
            f"| {sc.scenario_name} | {_fmt_months(sc.catalyst_timing_months)} "
            f"| {sc.burn_assumption} | {_fmt_pct(sc.pos_assumption)} "
            f"| {sc.financing_need} | {_fmt_m(sc.expected_value)} "
            f"| {_fmt_pct(sc.probability_cashout_before_catalyst)} |\n"
        )

    return f"""## K. Scenario Analysis

The following scenarios illustrate how changes in key assumptions affect the
capital-to-catalyst risk and expected value. Each scenario is run as an
independent Monte Carlo simulation with modified inputs.

| Scenario | Catalyst Timing | Burn Assumption | PoS | Financing Need | Financing rNPV | P(Cashout Before Catalyst) |
|---|---:|---|---:|---|---:|---:|
{rows}

> **Note:** Scenario values are modelled estimates based on modified input
> assumptions. They are not forecasts. Bull and Bear cases represent directional
> analysis, not bounds on possible outcomes."""


def _sensitivity_section(r: AuditResponse, req: AuditRequest) -> str:
    sensitivity = r.final_summary.sensitivity
    if not sensitivity:
        return "## L. Sensitivity Analysis\n\n_Sensitivity analysis not available._"

    rows = ""
    for sp in sensitivity:
        cashout_range = abs(sp.high_cashout_prob - sp.low_cashout_prob)
        ev_range = abs(sp.high_expected_value - sp.low_expected_value)
        rows += (
            f"| {sp.variable.replace('_', ' ').title()} "
            f"| {sp.low_label} | {sp.base_label} | {sp.high_label} "
            f"| {_fmt_pct(sp.low_cashout_prob)} → {_fmt_pct(sp.high_cashout_prob)} "
            f"| {_fmt_m(sp.low_expected_value)} → {_fmt_m(sp.high_expected_value)} |\n"
        )

    # Find most impactful variable on cashout risk
    if sensitivity:
        most_impactful = max(
            sensitivity,
            key=lambda x: abs(x.high_cashout_prob - x.low_cashout_prob),
        )
        impact_note = (
            f"The model is most sensitive to **{most_impactful.variable.replace('_', ' ')}** "
            f"in terms of capital-to-catalyst risk impact, suggesting that this is the "
            f"highest-value diligence variable."
        )
    else:
        impact_note = ""

    return f"""## L. Sensitivity Analysis

The following table shows how the model's two primary outputs — P(cashout before
catalyst) and financing-adjusted rNPV — change as individual input variables
are moved from low to high assumptions, holding all other inputs constant.

| Variable | Low Case | Base Case | High Case | Cashout Risk Range | rNPV Range |
|---|---|---|---|---|---|
{rows}

{impact_note}

> **Interpretation:** Sensitivity analysis identifies which input assumptions
> drive model results most strongly. Variables with high sensitivity represent
> the highest-priority diligence items, as small changes in those assumptions
> materially alter the risk and value profile."""


def _diligence_questions_section(r: AuditResponse) -> str:
    questions = r.final_summary.diligence_questions
    if not questions:
        return "## M. Key Diligence Questions\n\n_No questions generated._"

    q_list = "\n".join(f"{i + 1}. {q}" for i, q in enumerate(questions))

    return f"""## M. Key Diligence Questions for Investment Teams

Based on model findings, the following questions represent priority diligence
items for investment committee consideration:

{q_list}"""


def _assumptions_section(r: AuditResponse) -> str:
    assumption_list = "\n".join(f"- {a}" for a in r.assumptions)
    warning_list = "\n".join(f"- {w}" for w in r.warnings)

    return f"""## N. Model Assumptions and Limitations

### Model Assumptions Applied in This Analysis

{assumption_list}

### Limitations and Warnings

{warning_list}

### Additional Limitations

- Cox survival coefficients are untrained MVP assumptions; they have not been
  calibrated to historical biotech financing failure outcome data.
- Signal weights for the Bayesian PoS model are not trained on clinical approval
  data; they represent directional expert priors.
- Clinical milestone timing uses a Gamma distribution parameterised from the stated
  management timeline; actual timelines may differ materially.
- The model does not capture strategic transactions, partnerships, licensing revenue,
  or non-dilutive financing that could extend runway.
- rNPV outputs are mechanical functions of user-supplied asset value assumptions.
- Public filings may not reflect recent financing activity, confidential partnership
  discussions, or protocol amendments not yet disclosed.
- The Jensen-Shannon divergence disclosure score is based on user-supplied narrative
  and audit distributions; it does not independently analyse SEC filings or press releases."""


def _conclusion_section(r: AuditResponse, req: AuditRequest) -> str:
    ctc = r.capital_to_catalyst
    pos = r.success_probability
    disc = r.disclosure_consistency
    burn = r.burn_regime
    s = r.final_summary

    cashout_pct = _fmt_pct(ctc.probability_cashout_before_catalyst)
    catalyst_type = req.clinical.catalyst_type.replace("_", " ")

    if s.risk_classification == "Critical Risk":
        conclusion_body = (
            f"CatalystLens classifies {r.company_name} ({r.ticker}) as **Critical Capital-to-Catalyst Risk**. "
            f"There is a modelled probability of {cashout_pct} that capital is exhausted before "
            f"the stated {catalyst_type} milestone. The model does not primarily flag the program "
            f"as technically unviable — the Bayesian posterior PoS is {_fmt_pct(pos.posterior_mean)} "
            f"— but rather identifies a severe financing-timing mismatch. Under current assumptions, "
            f"the company is unlikely to reach the catalyst without a material capital raise. "
            f"For an investment firm, the primary diligence priority is not whether the asset can "
            f"succeed clinically, but whether the company can finance itself through a credible data "
            f"event without unacceptable dilution to existing shareholders."
        )
    elif s.risk_classification == "High Risk":
        conclusion_body = (
            f"CatalystLens classifies {r.company_name} ({r.ticker}) as **High Capital-to-Catalyst Risk**. "
            f"The modelled probability of capital exhaustion before the {catalyst_type} is {cashout_pct}. "
            f"While the technical risk profile (Bayesian PoS: {_fmt_pct(pos.posterior_mean)}) is "
            f"the direct scientific question, the interaction between financing timing and clinical "
            f"delay is the primary risk driver. Investors should assess whether the company has a "
            f"credible path to the data event without requiring dilutive financing under adverse conditions."
        )
    elif s.risk_classification == "Moderate Risk":
        conclusion_body = (
            f"CatalystLens classifies {r.company_name} ({r.ticker}) as **Moderate Capital-to-Catalyst Risk**. "
            f"There is a {cashout_pct} modelled probability of capital exhaustion before the {catalyst_type}. "
            f"While financing risk is present, it is not the dominant risk under base-case assumptions. "
            f"The investment thesis should be stress-tested against bear-case burn and clinical delay scenarios."
        )
    else:
        conclusion_body = (
            f"CatalystLens classifies {r.company_name} ({r.ticker}) as **Low Capital-to-Catalyst Risk**. "
            f"The modelled probability of capital exhaustion before the {catalyst_type} is {cashout_pct}. "
            f"Under base-case assumptions, the company appears adequately capitalised to reach the stated "
            f"catalyst window. The primary risk appears to be technical (Bayesian PoS: {_fmt_pct(pos.posterior_mean)}) "
            f"rather than financial."
        )

    risk_table = f"""| Risk Dimension | Assessment | Primary Driver |
|---|---|---|
| Technical / Scientific Risk | {_fmt_pct(1.0 - pos.posterior_mean)} implied failure probability | Bayesian posterior PoS: {_fmt_pct(pos.posterior_mean)} |
| Financing / Capital Risk | {_fmt_pct(ctc.probability_cashout_before_catalyst)} cashout probability | Cox-adjusted survival model |
| Timing Risk | {r.milestone_timing.delay_factor:.2f}x stated delay | Gamma milestone model |
| Disclosure / Narrative Risk | {disc.gap_classification.title()} | JSD: {disc.jsd_score:.3f} |
| Burn Trajectory Risk | {burn.regime.title()} | Mean QoQ: {burn.burn_acceleration:+.1%} |"""

    return f"""## O. Final Investment Risk Conclusion

{conclusion_body}

### Risk Dimension Summary

{risk_table}

---

*This report was generated by CatalystLens. It is not investment advice.
All model outputs are probabilistic estimates. This system should complement,
not replace, professional analyst diligence and institutional risk management processes.*"""


def _data_quality_section(r: AuditResponse) -> str:
    dq = r.data_quality
    score_label = {"high": "High ✓", "moderate": "Moderate ⚠", "low": "Low ✗"}.get(
        dq.data_quality_score, dq.data_quality_score
    )
    limitations = "\n".join(f"- {lim}" for lim in dq.primary_limitations) if dq.primary_limitations else "- None identified."

    return f"""## P. Data Quality Assessment

| Dimension | Completeness | Notes |
|---|---|---|
| Financial Data | {dq.financial_data_completeness:.0%} | Burn history, liquidity, market inputs |
| Clinical Data | {dq.clinical_data_completeness:.0%} | Enrollment, timeline, complexity scores |
| Disclosure Data | {dq.disclosure_data_completeness:.0%} | Narrative vs structured audit categories |
| **Overall** | **{dq.overall_completeness:.0%}** | **{score_label}** |

### Primary Data Limitations

{limitations}

> Data quality affects model confidence. Low-completeness inputs reduce the
> reliability of probabilistic outputs. Treat low-quality model results as
> directional indicators only."""


def _model_validation_section(r: AuditResponse) -> str:
    v = r.validation_snapshot
    unavailable = (
        "\n\n> **Calibration warning:** Historical labeled datasets and frozen trained "
        "artifacts are not available for this run. Validation metrics are therefore "
        "reported as unavailable, and outputs remain assumption-based model estimates."
        if v.solvency_calibration_status == "research_mode" else ""
    )

    return f"""## Q. Model Validation Status

| Metric | Value |
|---|---:|
| Solvency Calibration Status | {v.solvency_calibration_status} |
| IPCW C-Index | {v.solvency_c_index_ipcw if v.solvency_c_index_ipcw is not None else "Unavailable"} |
| Integrated Brier Score | {v.solvency_integrated_brier_score if v.solvency_integrated_brier_score is not None else "Unavailable"} |
| ICI / 12-Month Calibration Error | {v.solvency_ici_12m if v.solvency_ici_12m is not None else "Unavailable"} |
| PoS Posterior Predictive Check | {v.pos_ppc_status} |
| Timing Coverage Check | {v.timing_interval_coverage_status} |

{unavailable}"""


def _financial_clock_decomposition_section(r: AuditResponse) -> str:
    sol = r.solvency
    cash = r.cash_path
    val = r.valuation

    return f"""## R. Financial Clock Decomposition

| Component | Value | Interpretation |
|---|---:|---|
| Simple Runway | {_fmt_months(sol.simple_runway_months)} | Static liquidity / current monthly burn |
| Cox-Weibull Median Failure Time | {_fmt_months(sol.median_failure_time)} | Hazard-model financing survival clock |
| Mechanical Cash Exhaustion Month | {cash.cash_exhaustion_month if cash.cash_exhaustion_month is not None else "Not reached"} | Literal monthly cash-balance exhaustion |
| Cash Shortfall at Exhaustion | {_fmt_m(cash.cash_shortfall_at_exhaustion)} | True deficit in exhaustion month before clipping |
| Maximum Cash Deficit | {_fmt_m(cash.maximum_cash_deficit)} | Peak cumulative deficit over simulated horizon |
| Capital Needed to Survive Horizon | {_fmt_m(cash.capital_needed_to_survive_horizon)} | Capital required to avoid negative cash through horizon |
| Cash Path Final State | {cash.final_state.replace("_", " ").title()} | Mechanical cash-path endpoint |
| Funded Through Catalyst | {_fmt_pct(val.p_funded_through_catalyst)} | Four-state valuation probability |
| Clean Refinancing | {_fmt_pct(val.p_refinancing_success)} | Four-state valuation probability |
| Distressed Financing | {_fmt_pct(val.p_distressed_financing)} | Four-state valuation probability |
| Program Discontinuation | {_fmt_pct(val.p_program_discontinuation)} | Four-state valuation probability |"""


def _planned_financing_section(req: AuditRequest, r: AuditResponse) -> str:
    events = req.financial.planned_financing_events
    if not events:
        return "## S. Planned Financing Events\n\n_No planned financing events supplied._"

    rows = ""
    for event in events:
        rows += (
            f"| {event.month} | {event.kind.replace('_', ' ').title()} "
            f"| {_fmt_m(event.gross_proceeds)} | {_fmt_m(event.net_proceeds)} |\n"
        )
    exhaustion = (
        str(r.cash_path.cash_exhaustion_month)
        if r.cash_path.cash_exhaustion_month is not None else "Not reached"
    )
    return f"""## S. Planned Financing Events

| Month | Kind | Gross Proceeds | Net Proceeds |
|---:|---|---:|---:|
{rows}

**Effect on mechanical cash exhaustion month:** {exhaustion}"""


def _provenance_appendix(r: AuditResponse) -> str:
    p = r.provenance

    def _rows(items) -> str:
        if not items:
            return "| _(None)_ | — | — | — | — |\n"
        return "".join(
            f"| {item.field} | {item.value} | {item.evidence.source_type} "
            f"| {item.evidence.source_id} | {item.evidence.locator or 'manual'} |\n"
            for item in items
        )

    manual_warning = (
        "\n\n> **Manual input warning:** manual inputs are unverified because no source-traced "
        "SEC, ClinicalTrials.gov, deck, or press-release evidence was attached."
        if p.provenance_status == "manual_inputs_unverified" else ""
    )

    return f"""## T. Provenance Appendix

**Provenance Status:** {p.provenance_status}
{manual_warning}

### Financial Input Evidence

| Field | Value | Source Type | Source ID | Locator |
|---|---:|---|---|---|
{_rows(p.financial_inputs)}

### Clinical Input Evidence

| Field | Value | Source Type | Source ID | Locator |
|---|---:|---|---|---|
{_rows(p.clinical_inputs)}

### Claim Evidence

| Field | Value | Source Type | Source ID | Locator |
|---|---:|---|---|---|
{_rows(p.claims)}"""


# ---------------------------------------------------------------------------
# Master report assembler
# ---------------------------------------------------------------------------

def generate_full_report(r: AuditResponse, req: AuditRequest) -> str:
    """
    Assemble the complete institutional diligence report as Markdown.

    All sections are generated independently and joined.
    """
    sections: List[str] = [
        _header(r, req),
        _data_quality_section(r),
        _model_validation_section(r),
        _financial_clock_decomposition_section(r),
        _planned_financing_section(req, r),
        _executive_summary(r, req),
        _ic_snapshot(r, req),
        _capital_runway_section(r, req),
        _burn_regime_section(r, req),
        _clinical_catalyst_section(r, req),
        _bayesian_pos_section(r, req),
        _ctc_section(r, req),
        _dilution_section(r, req),
        _disclosure_section(r, req),
        _valuation_section(r, req),
        _scenario_section(r, req),
        _sensitivity_section(r, req),
        _diligence_questions_section(r),
        _assumptions_section(r),
        _provenance_appendix(r),
        _conclusion_section(r, req),
    ]
    return "\n\n---\n\n".join(sections)
